// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzqwecjzjoyrvdfkhwhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6cXdlY2p6am95cnZkZmtod2hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNzk2NzgsImV4cCI6MjA2OTc1NTY3OH0.tc7g_ttwfgGct4YYnMg3Jer5AmRloMUrCGMx1CXp_yg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});